@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":ClinicParser" as ClinicParser LOGIC_COLOR
participant ":AddCommandParser" as AddCommandParser LOGIC_COLOR
participant ":AddCommand" as AddCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "model:Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("add ct/s \n n/John Doe p/98766789"...")
activate LogicManager

LogicManager -> ClinicParser : parseCommand("add ct/s \n n/John Doe p/98766789"...")
activate ClinicParser

create AddCommandParser
ClinicParser -> AddCommandParser
activate AddCommandParser

AddCommandParser --> ClinicParser
deactivate AddCommandParser

ClinicParser -> AddCommandParser : parse("ct/s n/John Doe \n p/98766789"..."")
activate AddCommandParser

create AddCommand
AddCommandParser -> AddCommand
activate AddCommand

AddCommand --> AddCommandParser
deactivate AddCommand

AddCommandParser --> ClinicParser
deactivate AddCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
AddCommandParser -[hidden]-> ClinicParser
destroy AddCommandParser

ClinicParser --> LogicManager
deactivate ClinicParser

LogicManager -> AddCommand : execute(model)
activate AddCommand
AddCommand -> Model ++ : hasSupplier(supplierToAdd)
Model --> AddCommand -- :
AddCommand -> Model : addSupplier(supplierToAdd)
create CommandResult

AddCommand -> CommandResult ++ : message
activate CommandResult

CommandResult --> AddCommand -- : commandResult

deactivate CommandResult

AddCommand --> LogicManager -- : commandResult

ref over LogicManager,  Model : Execution of the Add Command Sequence Diagram
deactivate AddCommand

[<--LogicManager
deactivate LogicManager
@enduml
