@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Clinic *-right-> "1" UniqueSupplierList
Clinic *-left-> "1" UniqueWarehouseList

UniqueSupplierList o-right-> Supplier
UniqueWarehouseList o-left-> Warehouse

Supplier *--> Name
Supplier *--> Phone
Supplier *--> Email
Supplier *--> Remark
Supplier *--> Product
Warehouse *--> Name
Warehouse *--> Phone
Warehouse *--> Address
Warehouse *--> Remark
Warehouse *--> Product
@enduml
