@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Clinic *-down-> "1" UniqueSupplierList
Clinic *-left-> "1" UniqueWarehouseList
Clinic *-right-> "1" UniqueTagList
UniqueTagList -[hidden]down- UniqueSupplierList
UniqueTagList -[hidden]down- UniqueSupplierList

UniqueTagList *-right-> "*" Tag
UniqueSupplierList o-right-> Supplier
UniqueWarehouseList o-left-> Warehouse

Supplier -up-> "*" Tag

Supplier *--> Name
Supplier *--> Phone
Supplier *--> Email
Supplier *--> Product
Warehouse *--> Name
Warehouse *--> Phone
Warehouse *--> Address
Warehouse *--> Product
@enduml
