@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":ClinicParser" as ClinicParser LOGIC_COLOR
participant ":DeleteCommandParser" as DeleteCommandParser LOGIC_COLOR
participant ":DeleteCommand" as DeleteCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "model:Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("delete ct/s i/1")
activate LogicManager

LogicManager -> ClinicParser : parseCommand("delete ct/s i/1")
activate ClinicParser

create DeleteCommandParser
ClinicParser -> DeleteCommandParser
activate DeleteCommandParser

DeleteCommandParser --> ClinicParser
deactivate DeleteCommandParser

ClinicParser -> DeleteCommandParser : parse("ct/s i/1")
activate DeleteCommandParser

create DeleteCommand
DeleteCommandParser -> DeleteCommand
activate DeleteCommand

DeleteCommand --> DeleteCommandParser
deactivate DeleteCommand

DeleteCommandParser --> ClinicParser
deactivate DeleteCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteCommandParser -[hidden]-> ClinicParser
destroy DeleteCommandParser

ClinicParser --> LogicManager
deactivate ClinicParser

LogicManager -> DeleteCommand : execute(model)
activate DeleteCommand
ref over DeleteCommand, Model
Execution of DeleteCommand
end


DeleteCommand --> LogicManager
deactivate DeleteCommand

[<--LogicManager
deactivate LogicManager
@enduml
