@startuml
start
:User enters delete commands with relevant prefixes;
:Parse command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([required prefixes present & all values valid])
    :Generate Parse Exception;
    if () then ([is supplier/warehouse deletion])
        :Generate new DeleteCommand
        without a product name;
        :Execute DeleteCommand;

        if () then([supplier])
        :Remove the target supplier;
        else ([warehouse])
        :Remove the target warehouse;
        endif
    else ([is product deletion])
        :Generate new DeleteCommand
        without a product name;
        :Execute DeleteCommand;

        if () then([product from supplier])
            :Identify the required supplier;
            :Remove the target product;
        else ([product from warehouse])
            :Identify the required warehouse;
            :Remove the target product;
        endif

    endif
        :Generate edit success message;
else ([else])
    :Generate Parse Exception;
endif
:Display result message to user;
stop
@enduml