@startuml
start
:User enters delete commands with relevant prefixes;
:Parse command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([required prefixes present & all values valid])
    :Generate new DeleteCommand;
    :Execute DeleteCommand;
    if () then ([index is out of bound])
        :Generate Command Exception;

    else ([else])
        :Retrieve supplier/warehouse
        by specified index;
        if () then ([is supplier-related deletion])
            if () then([supplier deletion])
            :Remove target supplier;
            else ([product deletion])
            : Retrieve matching product
            from the set of products
            in the supplier;
                if () then([product found])
                :Remove the target product;
                else ([product not found])
                :Generate Command Exception;
                endif
            endif
        else ([is warehouse-related deletion])
            if () then([warehouse deletion])
            :Remove target warehouse;
            else ([product deletion])
            : Retrieve matching product
            from the set of products
            in the warehouse;
                if () then([product found])
                :Remove the target product;
                else ([product not found])
                :Generate Command Exception;
                endif
            endif
        endif
    endif
else ([else])
    :Generate Parse Exception;
endif
:Display result message to user;
stop
@enduml
