@startuml
!include style.puml

mainframe sd Create appropriate EditDesciptor
box Logic LOGIC_COLOR_T1
participant ":EditCommandParser" as EditCommandParser LOGIC_COLOR
participant "editDescriptor:EditSupplierDescriptor" as EditSupplierDescriptor LOGIC_COLOR
participant "editDescriptor:EditWarehouseDescriptor" as EditWarehouseDescriptor LOGIC_COLOR
end box

activate EditCommandParser

alt SUPPLIER
EditCommandParser -> EditCommandParser : parseSupplierForEditing(editSupplierDescriptor, argMultimap)
activate EditCommandParser
EditCommandParser -> EditCommandParser : parseGeneralDetails(editSupplierDescriptor, argMultimap)
activate EditCommandParser

EditCommandParser --> EditCommandParser
deactivate EditCommandParser

EditCommandParser --> EditCommandParser
deactivate EditCommandParser

create EditSupplierDescriptor
EditCommandParser -> EditSupplierDescriptor
activate EditSupplierDescriptor
EditSupplierDescriptor --> EditCommandParser
deactivate EditSupplierDescriptor

else WAREHOUSE
EditCommandParser -> EditCommandParser : parseWarehouseForEditing(editWarehouseDescriptor, argMultimap)
activate EditCommandParser
EditCommandParser -> EditCommandParser : parseGeneralDetails(editWarehouseDescriptor, argMultimap)
activate EditCommandParser


EditCommandParser --> EditCommandParser
deactivate EditCommandParser

EditCommandParser --> EditCommandParser
deactivate EditCommandParser

create EditWarehouseDescriptor
EditCommandParser -> EditWarehouseDescriptor
activate EditWarehouseDescriptor
EditWarehouseDescriptor --> EditCommandParser
deactivate EditWarehouseDescriptor

end
@enduml
