@startuml

!include style.puml

mainframe sd Tokenising and retrieving of values from user input
box Logic LOGIC_COLOR_T1
participant ":EditCommandParser" as EditCommandParser LOGIC_COLOR
participant ":ArgumentTokenizer" as ArgumentTokenizer <<static>> LOGIC_COLOR
participant "argMultimap:ArgumentMultimap" as ArgumentMultimap LOGIC_COLOR
end box

activate EditCommandParser

EditCommandParser -> ArgumentTokenizer : tokenize(...)
activate ArgumentTokenizer
create ArgumentMultimap
ArgumentTokenizer --> ArgumentMultimap
activate ArgumentMultimap
ArgumentMultimap --> ArgumentTokenizer
deactivate
ArgumentTokenizer --> EditCommandParser : argMultimap
deactivate ArgumentTokenizer

EditCommandParser -> ArgumentMultimap : getValue(PREFIX_TYPE), getValue(PREFIX_INDEX)
activate ArgumentMultimap
ArgumentMultimap --> EditCommandParser : type, index
deactivate ArgumentMultimap

@enduml
