@startuml
!include style.puml

mainframe sd Parsing Warehouse specific details

box Logic LOGIC_COLOR_T1
participant ":EditCommandParser" as EditCommandParser LOGIC_COLOR
participant "argMultimap:ArgumentMultimap" as ArgumentMultimap LOGIC_COLOR
participant ":ParserUtil" as ParserUtil LOGIC_COLOR
participant "editDescriptor:EditWarehouseDescriptor" as EditWarehouseDescriptor LOGIC_COLOR
end box

opt Address prefix present
EditCommandParser -> ArgumentMultimap : getValue(PREFIX_ADDRESS)
activate EditCommandParser
activate ArgumentMultimap
ArgumentMultimap --> EditCommandParser : Address
deactivate ArgumentMultimap

EditCommandParser -> ParserUtil : parseAddress(Address)
activate ParserUtil
ParserUtil --> EditCommandParser : parsedAddress
deactivate ParserUtil

EditCommandParser -> EditWarehouseDescriptor : setAddress(parsedAddress)
activate EditWarehouseDescriptor
deactivate EditWarehouseDescriptor
end

[<-- EditCommandParser : editDescriptor
deactivate EditCommandParser

@enduml