@startuml
!include style.puml

mainframe sd Parsing Supplier specific details

box Logic LOGIC_COLOR_T1
participant ":EditCommandParser" as EditCommandParser LOGIC_COLOR
participant "argMultimap:ArgumentMultimap" as ArgumentMultimap LOGIC_COLOR
participant ":ParserUtil" as ParserUtil LOGIC_COLOR
participant "editDescriptor:EditSupplierDescriptor" as EditSupplierDescriptor LOGIC_COLOR
end box

opt Email prefix present
EditCommandParser -> ArgumentMultimap : getValue(PREFIX_EMAIL)
activate EditCommandParser
activate ArgumentMultimap
ArgumentMultimap --> EditCommandParser : Email
deactivate ArgumentMultimap

EditCommandParser -> ParserUtil : parseEmail(Email)
activate ParserUtil
ParserUtil --> EditCommandParser : parsedEmail
deactivate ParserUtil

EditCommandParser -> EditSupplierDescriptor : setEmail(parsedEmail)
activate EditSupplierDescriptor
deactivate EditSupplierDescriptor
end

[<-- EditCommandParser : editDescriptor
deactivate EditCommandParser

@enduml
