@startuml
start
:User enters view commands with relevant prefixes;
:Parse user input;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([no command specified])
    :Create new Help Command;
    :Execute Help Command;
    :Generate generic help message of all commands;

else ([command specified])
    if () then ([valid command])
    :Create new Help command;
    :Execute Help Command;
    :Generate help message of specified command;
    else ([wrong input])
    :Generate error message specifying
    wrong command specified or too
    many arguments given;
    endif
endif
:Display result message to user;
stop

@enduml