@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

package Logic {

package Parser {
Interface Parser <<Interface>>
Class ClinicParser
Class MacroParser
Class XYZCommandParser
Class CliSyntax
Class ParserUtil
Class ArgumentMultimap
Class ArgumentTokenizer
Class Prefix
}

package Command {
Class XYZCommand
Class CommandResult
Class "{abstract}\nCommand" as Command
}

Interface Logic <<Interface>>
Class LogicManager
}

package Model{
Class HiddenModel #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Logic

LogicManager .up.|> Logic
LogicManager -down->"1" ClinicParser
LogicManager -left->"1" MacroParser
ClinicParser .left.> XYZCommandParser: creates >

XYZCommandParser .down.> XYZCommand : creates >
XYZCommandParser .down.|> Parser
XYZCommandParser .down.> ArgumentMultimap
XYZCommandParser .down.> ArgumentTokenizer
XYZCommandParser .down.> CliSyntax
XYZCommandParser .down.> ParserUtil
ArgumentTokenizer .left.> ArgumentMultimap
CliSyntax .down.> Prefix
ParserUtil .down.> Prefix
ArgumentTokenizer .down.> Prefix
XYZCommand -up-|> Command
LogicManager .left.> Command : executes >

LogicManager --> Model
Command .right.> Model
note right of XYZCommand: XYZCommand = AddCommand, \nDeleteCommand, FindCommand, etc

Logic ..> CommandResult
LogicManager .down.> CommandResult
Command .up.> CommandResult
CommandResult -[hidden]-> Parser
@enduml
