@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyClinic <<Interface>>
Interface Model <<Interface>>
Interface ObservableList <<Interface>>
Class Clinic
Class ReadOnlyClinic
Class Model
Class ModelManager
Class UserPrefs
Class UserMacros
Class CommandHistory
Class ReadOnlyUserMacros <<Interface>>
Class ReadOnlyUserPrefs <<Interface>>
Class ReadOnlyCommandHistory <<Interface>>

Package Supplier {
Class Supplier
Class UniqueSupplierList
}

Package Warehouse {
Class Warehouse
Class UniqueWarehouseList
}

Package Macro {
Class Macro
Class UniqueMacroList
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

Clinic .up.|> ReadOnlyClinic

ModelManager .up.|> Model
Model .right.> ObservableList
ModelManager o--> "1" Clinic
ModelManager o--> "1" UserPrefs
ModelManager o--> "1" UserMacros
ModelManager o--> "1" CommandHistory

UserPrefs .up.|> ReadOnlyUserPrefs
UserMacros .up.|> ReadOnlyUserMacros
CommandHistory .up.|> ReadOnlyCommandHistory

Clinic *-down-> "1" UniqueSupplierList
UniqueSupplierList o--> "*" Supplier

Clinic *-down-> "1" UniqueWarehouseList
UniqueWarehouseList o--> "*" Warehouse

UserMacros *-down-> "1" UniqueMacroList
UniqueMacroList o--> "*" Macro


ModelManager -->"*" Supplier : filtered list
ModelManager -->"*" Warehouse : filtered list
ModelManager -->"*" Macro : observable list
@enduml
