@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyClinic <<Interface>>
Interface Model <<Interface>>
Interface ObservableList <<Interface>>
Class Clinic
Class ReadOnlyClinic
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs

Package Supplier {
Class Supplier
Class Name
Class Phone
Class Email
Class Remark
Class Product
Class UniqueSupplierList
}

Package Tag{
Class Tag
}
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

Clinic .up.|> ReadOnlyClinic

ModelManager .up.|> Model
Model .right.> ObservableList
ModelManager o--> "1" Clinic
ModelManager o-left-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

Clinic *-down-> "1" UniqueSupplierList
UniqueSupplierList o--> "*" Supplier
Supplier *--> Name
Supplier *--> Phone
Supplier *--> Email
Supplier *--> "*" Tag
Supplier *--> Remark
Supplier *--> Product

ModelManager -->"1" Supplier : filtered list
@enduml
