@startuml
start
:User enters Remove Macro Command;


if () then ([alias is supplied])
  :Parse command arguments;
  if() then ([alias supplied is valid])
    :Create new RemoveMacroCommand;
    :Execute RemoveMacroCommand;
    if() then ([no macro with the specified alias exist])
      :Generate message indicating
      macro does not exist;
    else ([else])
      :Delete macro from model;
      :Generate success message;
    endif
  else ([else])
      :Generate message indicating
      invalid alias;
  endif
else ([else])
  :Generate message indicating
  invalid format;
endif
:Display result message to user;
stop
@enduml
