@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

Interface Storage <<Interface>>
Interface UserPrefsStorage <<Interface>>
Interface UserMacrosStorage <<Interface>>
Interface ClinicStorage <<Interface>>
Interface CommandHistoryStorage <<Interface>>

Class StorageManager
Class JsonUserPrefsStorage
Class JsonClinicStorage
Class JsonUserMacrosStorage
Class TextFileCommandHistoryStorage

StorageManager .up.|> Storage
StorageManager o-down-> UserPrefsStorage
StorageManager o-down-> ClinicStorage
StorageManager o-down-> UserMacrosStorage
StorageManager o-down-> CommandHistoryStorage

TextFileCommandHistoryStorage .up.|> CommandHistoryStorage
JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonClinicStorage .up.|> ClinicStorage
JsonUserMacrosStorage .up.|> UserMacrosStorage
JsonClinicStorage ..> JsonSerializableClinic
JsonUserMacrosStorage ..> JsonSerializableUserMacros
JsonSerializableUserMacros ..> JsonAdaptedMacro
JsonSerializableClinic ..> JsonAdaptedSupplier
JsonSerializableClinic ..> JsonAdaptedWarehouse
JsonAdaptedSupplier ..> JsonAdaptedProduct
JsonAdaptedWarehouse ..> JsonAdaptedProduct
JsonAdaptedProduct ..> JsonAdaptedTag
@enduml
