@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

title After command "list"

package Versions {
    class Version1 as "__vc0:VersionedClinic__"
    class Version2 as "__vc1:VersionedClinic__"
    class Version3 as "__vc2:VersionedClinic__"
}
Version1 -[hidden]right-> Version2
Version2 -[hidden]right-> Version3

class Pointer as "Current Version" #FFFFF

Pointer -up-> Version2

package UndoVersionStack {
    class UndoVersion0 as "__vc0:VersionedClinic__"
}

class TopOfStack as "Top of the Stack" #FFFFF

TopOfStack -up-> UndoVersion0

package RedoVersionStack {
    class RedoVersion0 as "__vc2:VersionedClinic__"
}

class TopOfStack2 as "Top of the Stack" #FFFFF

TopOfStack2 -up-> RedoVersion0
@end
