@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

title Initial version

package Versions {
    class Version1 as "__vc0:VersionedClinic__"
    class Version2 as "__vc1:VersionedClinic__"
    class Version3 as "__vc2:VersionedClinic__"
}
Version1 -[hidden]right-> Version2
Version2 -[hidden]right-> Version3
hide Version2
hide Version3


class Pointer as "Current Version" #FFFFF
Pointer -up-> Version1


package RedoVersionStack {
}

package UndoVersionStack {
}
@end
