@startuml
!include style.puml
mainframe sd executing ViewCommand
box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant "v:ViewCommand" as ViewCommand LOGIC_COLOR
participant "result:CommandResult" as CommandResult LOGIC_COLOR
participant "supplierList:List" as SupplierList LOGIC_COLOR
participant "warehouseList:List" as WarehouseList LOGIC_COLOR
participant "supplierPredicate:NameContainsKeywordsPredicateForSupplier" as SupplierPredicate LOGIC_COLOR
participant "warehousePredicate:NameContainsKeywordsPredicateForWarehouse" as WarehousePredicate LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

activate LogicManager
LogicManager -> ViewCommand : execute(model)
activate ViewCommand
ViewCommand -> Model : getFilteredSupplierList()
activate Model

Model --> ViewCommand : supplierList
deactivate

ViewCommand -> Model : getFilteredWarehouseList()
activate Model
Model --> ViewCommand : warehouseList
deactivate

alt SUPPLIER
ViewCommand -> SupplierList : get(index)
activate SupplierList
SupplierList --> ViewCommand : supplierToView
deactivate SupplierList

create SupplierPredicate
ViewCommand -> SupplierPredicate : supplierToView.getName().toString()
activate SupplierPredicate
SupplierPredicate --> ViewCommand
deactivate SupplierPredicate

ViewCommand -> Model : updateFilteredSupplierList(supplierPredicate)
activate Model
deactivate Model

create CommandResult
ViewCommand -> CommandResult : supplierPredicate
activate CommandResult
CommandResult --> ViewCommand
deactivate CommandResult
ViewCommand --> LogicManager : result
[<--LogicManager : result

else WAREHOUSE
ViewCommand -> WarehouseList : get(index)
activate WarehouseList
WarehouseList --> ViewCommand : warehouseToView
deactivate WarehouseList

create WarehousePredicate
ViewCommand -> WarehousePredicate : warehouseToView.getName().toString()
activate WarehousePredicate
WarehousePredicate --> ViewCommand
deactivate WarehousePredicate

ViewCommand -> Model : updateFilteredWarehouseList(warehousePredicate)
activate Model
deactivate Model

create CommandResult
ViewCommand -> CommandResult : warehousePredicate
activate CommandResult
CommandResult --> ViewCommand
deactivate CommandResult
ViewCommand --> LogicManager : result
[<--LogicManager : result
deactivate LogicManager
end

@enduml